apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.ocp4.cn/redhat/ft-rest-service
    newTag: latest

patches:
  - target:
      kind: Route
      name: ft-rest-service
    patch: |-
      - op: replace
        path: /spec/host
        value: ft-rest-service-dev.apps.sandy.ocp4.cn

configMapGenerator:
  - name: ft-rest-service-config
    behavior: merge
    literals:
      - log_level=info
