apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - servicemonitor.yaml

configMapGenerator:
  - name: ft-rest-service-config
    literals:
      - log_level=info

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: registry.ocp4.cn/redhat/ft-rest-service
    newTag: latest
